-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employeerecord
(
    record_id serial NOT NULL,
    member_id integer,
    salary numeric(10, 2) NOT NULL,
    leave_taken integer DEFAULT 0,
    CONSTRAINT employeerecord_pkey PRIMARY KEY (record_id)
);

CREATE TABLE IF NOT EXISTS public.member
(
    member_id serial NOT NULL,
    member_name character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    dob date,
    email character varying(255) COLLATE pg_catalog."default",
    profile character varying(50) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    team_id integer,
    manager_id integer,
    CONSTRAINT member_pkey PRIMARY KEY (member_id),
    CONSTRAINT member_email_key UNIQUE (email),
    CONSTRAINT member_member_name_key UNIQUE (member_name)
);

CREATE TABLE IF NOT EXISTS public.team
(
    team_id serial NOT NULL,
    team_name character varying(255) COLLATE pg_catalog."default",
    manager_id integer,
    profile character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT team_pkey PRIMARY KEY (team_id),
    CONSTRAINT team_team_name_key UNIQUE (team_name)
);

ALTER TABLE IF EXISTS public.employeerecord
    ADD CONSTRAINT employeerecord_member_id_fkey FOREIGN KEY (member_id)
    REFERENCES public.member (member_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.member
    ADD CONSTRAINT member_manager_id_fkey FOREIGN KEY (manager_id)
    REFERENCES public.member (member_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.member
    ADD CONSTRAINT member_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES public.team (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;